user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;

    charset UTF-8;

    types {
        text/markdown  md;
    }
    default_type  application/octet-stream;
    charset_types text/plain text/html text/markdown;

    gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
