apiVersion: v1
kind: Namespace
metadata:
  name: gotti-dev
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gotti-dev
  namespace: gotti-dev
spec:
  interval: 1m0s
  ref:
    branch: deployment
  url: https://github.com/gotti/gotti.dev
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gotti-dev
  namespace: gotti-dev
spec:
  interval: 30s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotti-dev
  validation: client
