DefaultContentLanguage = "ja"
author = "ごっち"
baseURL = "https://gotti.dev/"
copyright = "Copyright © 2021"
disqusShortname = "gotti"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
hasCJKLanguage = true
languageCode = "ja"
theme = "hugo-theme-tokiwa"
title = "ごっちデヴ"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
description = """
ごっちでぶ
""" 
env = "production" # for Google Analytics and DISQUS.
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTEX$
useChineseFonts = false
postDateFormat = "2006-1-2"

[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
[social]
github = "http://github.com/gotti"
twitter = "http://twitter.com/0xg0tti"

[outputs]
home = ["HTML", "RSS", "JSON"]
