baseURL: https://gotti.dev
languageCode: ja-JP
defaultContentLanguage: jp
title: ごっちでぶ
theme: cupper-hugo-theme
enableGitInfo: true
params:
  description: ごっちでぶ
  homeMetaContent: ごっちでぶ
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to k8s on otaku house.
  dateFormat: 2006/1/2
  codePenUser: ごっち
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  moveFooterToHeader: false

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: Link
      url: /link/
      weight: 4
    - name: About
      url: /about/
      weight: 5
    - name: RSS
      url: /index.xml
      weight: 6

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
